### ISSUE TITLE
Use --nv instead of installing NVIDIA driver into container

### ISSUE THREAD

**Issue by GodloveD** [clemsonciti/singularity-images#1]
With the release of [Singularity v.2.3](https://github.com/singularityware/singularity/releases) it's no longer necessary (and in fact not recommended) to install host specific NVIDIA drivers into the container itself.  

Now using `--nv` will bind mount all necessary libraries into the container at runtime.  This keeps your container portable.

**Comment by shwina** [comment]
@GodloveD thank you! Excited to give this a try.

**Comment by shwina** [comment]
This worked great for us. Thanks, @GodloveD!
